[build-system]
requires = ["setuptools>=61.0.0"]
build-backend = "setuptools.build_meta"

[project]
name = "open-llm-proxy"
version = "0.1.0"
description = "Lightweight litellm Router proxy"
readme = "README.md"
requires-python = ">=3.10"
dependencies = [
    "litellm",
    "httpx[http2]",
    "pyyaml"
]

[project.optional-dependencies]
dev = [
    "pytest"
]
